Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -54,11 +54,11 @@ jobs:
 
       # Function to trigger the notebook job
       trigger_notebook_job() {
-        local token=$1
+        # local token=$1
         echo "Triggering Fabric Notebook Job with access token..."
         response=$(curl -s -X POST "https://api.fabric.microsoft.com/v1/workspaces/$(FABRICWORKSPACEVAR)/items/$(ARTIFACTIDVAR)/jobs/instances?jobType=RunNotebook" \
           -H "Content-Type: application/json" \
-          -H "Authorization: Bearer ${token}" \
+          -H "Authorization: Bearer $(TOKEN)" \
           -d '{
                 "executionData": {
                     "parameters": {},
@@ -92,17 +92,17 @@ jobs:
       
       echo "Testing token retrieval separately..."
 
-      test_token_response=$(curl -X POST "https://login.microsoftonline.com/c5e52224-ee99-4449-86e4-9f71d30f361b/oauth2/v2.0/token" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=e4f3d468-692b-4545-9376-d50c634767aa&scope=https://api.fabric.microsoft.com/.default&client_secret=$(CLIENTSECRETVAR)&grant_type=client_credentials")
+      # test_token_response=$(curl -X POST "https://login.microsoftonline.com/c5e52224-ee99-4449-86e4-9f71d30f361b/oauth2/v2.0/token" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=e4f3d468-692b-4545-9376-d50c634767aa&scope=https://api.fabric.microsoft.com/.default&client_secret=$(CLIENTSECRETVAR)&grant_type=client_credentials")
 
-      # Print the raw response
-      echo "Raw Token Response: $test_token_response"      
-      test_access_token=$(echo "$test_token_response" | jq -r '.access_token')
+      # # Print the raw response
+      # echo "Raw Token Response: $test_token_response"      
+      # test_access_token=$(echo "$test_token_response" | jq -r '.access_token')
   
 
-      if [[ -z "$test_access_token" || "$test_access_token" == "null" ]]; then
-        echo "Error: Failed to retrieve access token."
-        echo "Response: $test_token_response"
-        exit 1
-      else
-        echo "Successfully retrieved access token: $test_access_token"
-      fi
+      # if [[ -z "$test_access_token" || "$test_access_token" == "null" ]]; then
+      #   echo "Error: Failed to retrieve access token."
+      #   echo "Response: $test_token_response"
+      #   exit 1
+      # else
+      #   echo "Successfully retrieved access token: $test_access_token"
+      # fi
